# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ejemplo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1017, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtNum1 = QtWidgets.QTextEdit(self.centralwidget)
        self.txtNum1.setGeometry(QtCore.QRect(230, 70, 291, 61))
        self.txtNum1.setObjectName("txtNum1")
        self.txtNum2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txtNum2.setGeometry(QtCore.QRect(230, 160, 291, 61))
        self.txtNum2.setObjectName("txtNum2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 280, 541, 111))
        self.label.setStyleSheet("color: rgb(85, 85, 255);\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.btnSumar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSumar.setGeometry(QtCore.QRect(600, 70, 111, 51))
        self.btnSumar.setObjectName("btnSumar")
        self.btnCerra = QtWidgets.QPushButton(self.centralwidget)
        self.btnCerra.setGeometry(QtCore.QRect(860, 70, 111, 41))
        self.btnCerra.setObjectName("btnCerra")
        self.btnRestar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRestar.setGeometry(QtCore.QRect(600, 140, 111, 51))
        self.btnRestar.setObjectName("btnRestar")
        self.btnMulti = QtWidgets.QPushButton(self.centralwidget)
        self.btnMulti.setGeometry(QtCore.QRect(600, 210, 111, 51))
        self.btnMulti.setObjectName("btnMulti")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1017, 26))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuIr_a_Arboles = QtWidgets.QMenu(self.menuArchivo)
        self.menuIr_a_Arboles.setObjectName("menuIr_a_Arboles")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionArboles_Hamiltonianos = QtWidgets.QAction(MainWindow)
        self.actionArboles_Hamiltonianos.setObjectName("actionArboles_Hamiltonianos")
        self.actionArboles_Binarios = QtWidgets.QAction(MainWindow)
        self.actionArboles_Binarios.setObjectName("actionArboles_Binarios")
        self.menuIr_a_Arboles.addSeparator()
        self.menuIr_a_Arboles.addAction(self.actionArboles_Hamiltonianos)
        self.menuIr_a_Arboles.addAction(self.actionArboles_Binarios)
        self.menuArchivo.addAction(self.menuIr_a_Arboles.menuAction())
        self.menuArchivo.addSeparator()
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        self.btnCerra.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ejemplo de GUI en PYQT"))
        self.txtNum1.setToolTip(_translate("MainWindow", "Ingrese un entero"))
        self.txtNum2.setToolTip(_translate("MainWindow", "Ingrese un entero"))
        self.label.setText(_translate("MainWindow", "El resultado es:"))
        self.btnSumar.setText(_translate("MainWindow", "Sumar"))
        self.btnCerra.setText(_translate("MainWindow", "Cerra Ventana"))
        self.btnRestar.setText(_translate("MainWindow", "Restar"))
        self.btnMulti.setText(_translate("MainWindow", "Multiplicar"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuIr_a_Arboles.setTitle(_translate("MainWindow", "Ir a Arboles"))
        self.actionArboles_Hamiltonianos.setText(_translate("MainWindow", "Arboles Hamiltonianos"))
        self.actionArboles_Binarios.setText(_translate("MainWindow", "Arboles Binarios"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
